runtime: custom
env: flex

endpoints_api_service:
  name: 'your-project-id.appspot.com'
  config_id: '2017-09-01r0'

resources:
  cpu: 1
  memory_gb: 0.9
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.7
